### ISSUE TITLE
The Log out button 

### ISSUE THREAD

**Issue by JavierMachucaA** [owrrpon/modhyobitto-angular#1]
I think this it's a great project, and if you want i made some simples ideas for improve this repo. i propose the log out button.
🦖 👍 😄 @owrrpon

**Comment by owrrpon** [comment]
Hello @JavierMachucaA , Thanks for your interest! As the logout button is almost entirely a UX choice, I decided to skip that. However, feel free to use the codebase and tweak and/or add new elements. Let me know once you are done with the updates! :)
